{% set version = "8.3.0" %}
{% set build = 0 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'mpich' %}
# prioritize mpich variant, which was previously the only option, via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: esmf
  version: {{ version }}

source:
  url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0ff43ede83d1ac6beabd3d5e2a646f7574174b28a48d1b9f2c318a054ba268fd

build:
  number: {{ build }}
  skip: true  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `esmf * mpi_mpich_*` for mpich
  # `esmf * mpi_*` for any mpi
  # `esmf * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - perl
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
  host:
    # need to list netcdf-fortran, hdf5 and libnetcdf twice to get version
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_prefix }}_*
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - netcdf-fortran * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
    - openssh  # [mpi == 'openmpi']

test:
  commands:
    - ESMF_PrintInfo
    - ESMF_RegridWeightGen --help

about:
  home: http://earthsystemmodeling.org/
  license: NCSA
  license_file: LICENSE
  summary: |
    The Earth System Modeling Framework (ESMF) is software for building and
    coupling weather, climate, and related models.'

extra:
  recipe-maintainers:
    - ocefpaf
    - rokuingh
    - xylar
