#{% set version = "7.0.0" %}
{% set version = "7.1.0.dev54" %}
{% set ver = version.replace(".", "_") %}

package:
  name: esmf
  version: {{ version }}

source:
#  url: http://downloads.sourceforge.net/project/esmf/ESMF_{{ ver }}/esmf_{{ ver }}_src.tar.gz
#  sha256: b2ac25f78c4bded006360230bd229953909f2a9f9e71b732833c240edc7707b1
  url: https://sourceforge.net/code-snapshots/git/e/es/esmf/esmf.git/esmf-esmf-137e4eac0f5a9f5191120cc77a7b34f66f0c3ddf.zip
  sha256: 91e97d506210c1fe927b41d5664a3174ccb75d0652297b69605d4012aafcf085

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - netcdf-fortran 4.4.*
    - hdf5 1.10.1
    - perl 5.22.2.1
    - gcc  # [not win]
    - mpich
  run:
    - netcdf-fortran 4.4.*
    - hdf5 1.10.1
    - libgcc  # [not win]
    - mpich

test:
  commands:
    - ESMF_Info
    - ESMF_RegridWeightGen --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.earthsystemmodeling.org/
  license: The University of Illinois/NCSA Open Source License (NCSA)
  summary: 'The Earth System Modeling Framework (ESMF) is software for building and coupling weather, climate, and related models.'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - rokuingh
