{% set version = "7.1.0" %}
{% set ver = version.replace(".", "_") %}

package:
  name: esmf
  version: {{ version }}

source:
  git_url: git://git.code.sf.net/p/esmf/esmf
  git_tag: ESMF_7_1_0r

build:
  number: 1007
  skip: True  # [win]

requirements:
  build:
    - perl
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - netcdf-fortran
    - mpich
  run:
    - netcdf-fortran
    - mpich

test:
  commands:
    - ESMF_Info
    - ESMF_RegridWeightGen --help

about:
  home: http://www.earthsystemmodeling.org/
  license: University of Illinois/NCSA (NCSA)
  summary: |
    The Earth System Modeling Framework (ESMF) is software for building and
    coupling weather, climate, and related models.'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - rokuingh
